version: '3.4'

networks:
  frontend:
  backend:

services:
  eventcatalog:
    image: event/eventcatalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      ExternalBaseUrl: http://localhost:7810
      DatabaseServer: mssqlserver
      DatabaseName: EventDBdocker
      DatabaseUser: sa
      DatabasePassword: P@ssword(!)
    ports:
      - "7810:80"
    depends_on:
      - mssqlserver
    networks:
     - frontend
     - backend
    container_name: productserver



  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssword(!)
    ports:
     - "1448:1433"
    container_name: mssqlserver
    networks:
      - backend